"""autogenerated by genpy from grasping_controller/MakeIKRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MakeIKRequest(genpy.Message):
  _md5sum = "2296530322c13c2206bc7350feeca923"
  _type = "grasping_controller/MakeIKRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 x_obj
float64 y_obj
float64 z_obj
float64 xr_obj
float64 yr_obj
float64 zr_obj
float64 w_obj
float64 x_gripper
float64 y_gripper
float64 z_gripper
float64 xr_gripper
float64 yr_gripper
float64 zr_gripper
float64 w_gripper

"""
  __slots__ = ['x_obj','y_obj','z_obj','xr_obj','yr_obj','zr_obj','w_obj','x_gripper','y_gripper','z_gripper','xr_gripper','yr_gripper','zr_gripper','w_gripper']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x_obj,y_obj,z_obj,xr_obj,yr_obj,zr_obj,w_obj,x_gripper,y_gripper,z_gripper,xr_gripper,yr_gripper,zr_gripper,w_gripper

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MakeIKRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.x_obj is None:
        self.x_obj = 0.
      if self.y_obj is None:
        self.y_obj = 0.
      if self.z_obj is None:
        self.z_obj = 0.
      if self.xr_obj is None:
        self.xr_obj = 0.
      if self.yr_obj is None:
        self.yr_obj = 0.
      if self.zr_obj is None:
        self.zr_obj = 0.
      if self.w_obj is None:
        self.w_obj = 0.
      if self.x_gripper is None:
        self.x_gripper = 0.
      if self.y_gripper is None:
        self.y_gripper = 0.
      if self.z_gripper is None:
        self.z_gripper = 0.
      if self.xr_gripper is None:
        self.xr_gripper = 0.
      if self.yr_gripper is None:
        self.yr_gripper = 0.
      if self.zr_gripper is None:
        self.zr_gripper = 0.
      if self.w_gripper is None:
        self.w_gripper = 0.
    else:
      self.x_obj = 0.
      self.y_obj = 0.
      self.z_obj = 0.
      self.xr_obj = 0.
      self.yr_obj = 0.
      self.zr_obj = 0.
      self.w_obj = 0.
      self.x_gripper = 0.
      self.y_gripper = 0.
      self.z_gripper = 0.
      self.xr_gripper = 0.
      self.yr_gripper = 0.
      self.zr_gripper = 0.
      self.w_gripper = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_14d.pack(_x.x_obj, _x.y_obj, _x.z_obj, _x.xr_obj, _x.yr_obj, _x.zr_obj, _x.w_obj, _x.x_gripper, _x.y_gripper, _x.z_gripper, _x.xr_gripper, _x.yr_gripper, _x.zr_gripper, _x.w_gripper))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 112
      (_x.x_obj, _x.y_obj, _x.z_obj, _x.xr_obj, _x.yr_obj, _x.zr_obj, _x.w_obj, _x.x_gripper, _x.y_gripper, _x.z_gripper, _x.xr_gripper, _x.yr_gripper, _x.zr_gripper, _x.w_gripper,) = _struct_14d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_14d.pack(_x.x_obj, _x.y_obj, _x.z_obj, _x.xr_obj, _x.yr_obj, _x.zr_obj, _x.w_obj, _x.x_gripper, _x.y_gripper, _x.z_gripper, _x.xr_gripper, _x.yr_gripper, _x.zr_gripper, _x.w_gripper))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 112
      (_x.x_obj, _x.y_obj, _x.z_obj, _x.xr_obj, _x.yr_obj, _x.zr_obj, _x.w_obj, _x.x_gripper, _x.y_gripper, _x.z_gripper, _x.xr_gripper, _x.yr_gripper, _x.zr_gripper, _x.w_gripper,) = _struct_14d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_14d = struct.Struct("<14d")
"""autogenerated by genpy from grasping_controller/MakeIKResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MakeIKResponse(genpy.Message):
  _md5sum = "ec083468e9067c595612b436b8a4cd45"
  _type = "grasping_controller/MakeIKResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 joint_1
float64 joint_2
float64 joint_3
float64 joint_4
float64 joint_5
float64 joint_6


"""
  __slots__ = ['joint_1','joint_2','joint_3','joint_4','joint_5','joint_6']
  _slot_types = ['float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       joint_1,joint_2,joint_3,joint_4,joint_5,joint_6

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MakeIKResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.joint_1 is None:
        self.joint_1 = 0.
      if self.joint_2 is None:
        self.joint_2 = 0.
      if self.joint_3 is None:
        self.joint_3 = 0.
      if self.joint_4 is None:
        self.joint_4 = 0.
      if self.joint_5 is None:
        self.joint_5 = 0.
      if self.joint_6 is None:
        self.joint_6 = 0.
    else:
      self.joint_1 = 0.
      self.joint_2 = 0.
      self.joint_3 = 0.
      self.joint_4 = 0.
      self.joint_5 = 0.
      self.joint_6 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_6d.pack(_x.joint_1, _x.joint_2, _x.joint_3, _x.joint_4, _x.joint_5, _x.joint_6))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.joint_1, _x.joint_2, _x.joint_3, _x.joint_4, _x.joint_5, _x.joint_6,) = _struct_6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_6d.pack(_x.joint_1, _x.joint_2, _x.joint_3, _x.joint_4, _x.joint_5, _x.joint_6))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.joint_1, _x.joint_2, _x.joint_3, _x.joint_4, _x.joint_5, _x.joint_6,) = _struct_6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_6d = struct.Struct("<6d")
class MakeIK(object):
  _type          = 'grasping_controller/MakeIK'
  _md5sum = '899191b7022e78e02644dabd0dd8dee3'
  _request_class  = MakeIKRequest
  _response_class = MakeIKResponse
