/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/yk/catkin_ws/src/wsg_50_common/srv/Conf.srv
 *
 */


#ifndef WSG_50_COMMON_MESSAGE_CONF_H
#define WSG_50_COMMON_MESSAGE_CONF_H

#include <ros/service_traits.h>


#include <wsg_50_common/ConfRequest.h>
#include <wsg_50_common/ConfResponse.h>


namespace wsg_50_common
{

struct Conf
{

typedef ConfRequest Request;
typedef ConfResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Conf
} // namespace wsg_50_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wsg_50_common::Conf > {
  static const char* value()
  {
    return "0c7a1839200830facdc1205cf36615d5";
  }

  static const char* value(const ::wsg_50_common::Conf&) { return value(); }
};

template<>
struct DataType< ::wsg_50_common::Conf > {
  static const char* value()
  {
    return "wsg_50_common/Conf";
  }

  static const char* value(const ::wsg_50_common::Conf&) { return value(); }
};


// service_traits::MD5Sum< ::wsg_50_common::ConfRequest> should match 
// service_traits::MD5Sum< ::wsg_50_common::Conf > 
template<>
struct MD5Sum< ::wsg_50_common::ConfRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wsg_50_common::Conf >::value();
  }
  static const char* value(const ::wsg_50_common::ConfRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wsg_50_common::ConfRequest> should match 
// service_traits::DataType< ::wsg_50_common::Conf > 
template<>
struct DataType< ::wsg_50_common::ConfRequest>
{
  static const char* value()
  {
    return DataType< ::wsg_50_common::Conf >::value();
  }
  static const char* value(const ::wsg_50_common::ConfRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wsg_50_common::ConfResponse> should match 
// service_traits::MD5Sum< ::wsg_50_common::Conf > 
template<>
struct MD5Sum< ::wsg_50_common::ConfResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wsg_50_common::Conf >::value();
  }
  static const char* value(const ::wsg_50_common::ConfResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wsg_50_common::ConfResponse> should match 
// service_traits::DataType< ::wsg_50_common::Conf > 
template<>
struct DataType< ::wsg_50_common::ConfResponse>
{
  static const char* value()
  {
    return DataType< ::wsg_50_common::Conf >::value();
  }
  static const char* value(const ::wsg_50_common::ConfResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WSG_50_COMMON_MESSAGE_CONF_H
