/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/yk/catkin_ws/src/grasping_controller/srv/MakeIK.srv
 *
 */


#ifndef GRASPING_CONTROLLER_MESSAGE_MAKEIKREQUEST_H
#define GRASPING_CONTROLLER_MESSAGE_MAKEIKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace grasping_controller
{
template <class ContainerAllocator>
struct MakeIKRequest_
{
  typedef MakeIKRequest_<ContainerAllocator> Type;

  MakeIKRequest_()
    : x_obj(0.0)
    , y_obj(0.0)
    , z_obj(0.0)
    , xr_obj(0.0)
    , yr_obj(0.0)
    , zr_obj(0.0)
    , w_obj(0.0)
    , x_gripper(0.0)
    , y_gripper(0.0)
    , z_gripper(0.0)
    , xr_gripper(0.0)
    , yr_gripper(0.0)
    , zr_gripper(0.0)
    , w_gripper(0.0)  {
    }
  MakeIKRequest_(const ContainerAllocator& _alloc)
    : x_obj(0.0)
    , y_obj(0.0)
    , z_obj(0.0)
    , xr_obj(0.0)
    , yr_obj(0.0)
    , zr_obj(0.0)
    , w_obj(0.0)
    , x_gripper(0.0)
    , y_gripper(0.0)
    , z_gripper(0.0)
    , xr_gripper(0.0)
    , yr_gripper(0.0)
    , zr_gripper(0.0)
    , w_gripper(0.0)  {
    }



   typedef double _x_obj_type;
  _x_obj_type x_obj;

   typedef double _y_obj_type;
  _y_obj_type y_obj;

   typedef double _z_obj_type;
  _z_obj_type z_obj;

   typedef double _xr_obj_type;
  _xr_obj_type xr_obj;

   typedef double _yr_obj_type;
  _yr_obj_type yr_obj;

   typedef double _zr_obj_type;
  _zr_obj_type zr_obj;

   typedef double _w_obj_type;
  _w_obj_type w_obj;

   typedef double _x_gripper_type;
  _x_gripper_type x_gripper;

   typedef double _y_gripper_type;
  _y_gripper_type y_gripper;

   typedef double _z_gripper_type;
  _z_gripper_type z_gripper;

   typedef double _xr_gripper_type;
  _xr_gripper_type xr_gripper;

   typedef double _yr_gripper_type;
  _yr_gripper_type yr_gripper;

   typedef double _zr_gripper_type;
  _zr_gripper_type zr_gripper;

   typedef double _w_gripper_type;
  _w_gripper_type w_gripper;




  typedef boost::shared_ptr< ::grasping_controller::MakeIKRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grasping_controller::MakeIKRequest_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct MakeIKRequest_

typedef ::grasping_controller::MakeIKRequest_<std::allocator<void> > MakeIKRequest;

typedef boost::shared_ptr< ::grasping_controller::MakeIKRequest > MakeIKRequestPtr;
typedef boost::shared_ptr< ::grasping_controller::MakeIKRequest const> MakeIKRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grasping_controller::MakeIKRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grasping_controller::MakeIKRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace grasping_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/hydro/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/hydro/share/trajectory_msgs/cmake/../msg'], 'control_msgs': ['/opt/ros/hydro/share/control_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::grasping_controller::MakeIKRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grasping_controller::MakeIKRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasping_controller::MakeIKRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasping_controller::MakeIKRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasping_controller::MakeIKRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasping_controller::MakeIKRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grasping_controller::MakeIKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2296530322c13c2206bc7350feeca923";
  }

  static const char* value(const ::grasping_controller::MakeIKRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2296530322c13c22ULL;
  static const uint64_t static_value2 = 0x06bc7350feeca923ULL;
};

template<class ContainerAllocator>
struct DataType< ::grasping_controller::MakeIKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grasping_controller/MakeIKRequest";
  }

  static const char* value(const ::grasping_controller::MakeIKRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grasping_controller::MakeIKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x_obj\n\
float64 y_obj\n\
float64 z_obj\n\
float64 xr_obj\n\
float64 yr_obj\n\
float64 zr_obj\n\
float64 w_obj\n\
float64 x_gripper\n\
float64 y_gripper\n\
float64 z_gripper\n\
float64 xr_gripper\n\
float64 yr_gripper\n\
float64 zr_gripper\n\
float64 w_gripper\n\
";
  }

  static const char* value(const ::grasping_controller::MakeIKRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grasping_controller::MakeIKRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_obj);
      stream.next(m.y_obj);
      stream.next(m.z_obj);
      stream.next(m.xr_obj);
      stream.next(m.yr_obj);
      stream.next(m.zr_obj);
      stream.next(m.w_obj);
      stream.next(m.x_gripper);
      stream.next(m.y_gripper);
      stream.next(m.z_gripper);
      stream.next(m.xr_gripper);
      stream.next(m.yr_gripper);
      stream.next(m.zr_gripper);
      stream.next(m.w_gripper);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MakeIKRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grasping_controller::MakeIKRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grasping_controller::MakeIKRequest_<ContainerAllocator>& v)
  {
    s << indent << "x_obj: ";
    Printer<double>::stream(s, indent + "  ", v.x_obj);
    s << indent << "y_obj: ";
    Printer<double>::stream(s, indent + "  ", v.y_obj);
    s << indent << "z_obj: ";
    Printer<double>::stream(s, indent + "  ", v.z_obj);
    s << indent << "xr_obj: ";
    Printer<double>::stream(s, indent + "  ", v.xr_obj);
    s << indent << "yr_obj: ";
    Printer<double>::stream(s, indent + "  ", v.yr_obj);
    s << indent << "zr_obj: ";
    Printer<double>::stream(s, indent + "  ", v.zr_obj);
    s << indent << "w_obj: ";
    Printer<double>::stream(s, indent + "  ", v.w_obj);
    s << indent << "x_gripper: ";
    Printer<double>::stream(s, indent + "  ", v.x_gripper);
    s << indent << "y_gripper: ";
    Printer<double>::stream(s, indent + "  ", v.y_gripper);
    s << indent << "z_gripper: ";
    Printer<double>::stream(s, indent + "  ", v.z_gripper);
    s << indent << "xr_gripper: ";
    Printer<double>::stream(s, indent + "  ", v.xr_gripper);
    s << indent << "yr_gripper: ";
    Printer<double>::stream(s, indent + "  ", v.yr_gripper);
    s << indent << "zr_gripper: ";
    Printer<double>::stream(s, indent + "  ", v.zr_gripper);
    s << indent << "w_gripper: ";
    Printer<double>::stream(s, indent + "  ", v.w_gripper);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASPING_CONTROLLER_MESSAGE_MAKEIKREQUEST_H
