/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/yk/catkin_ws/src/grasping_controller/srv/MoveAll.srv
 *
 */


#ifndef GRASPING_CONTROLLER_MESSAGE_MOVEALL_H
#define GRASPING_CONTROLLER_MESSAGE_MOVEALL_H

#include <ros/service_traits.h>


#include <grasping_controller/MoveAllRequest.h>
#include <grasping_controller/MoveAllResponse.h>


namespace grasping_controller
{

struct MoveAll
{

typedef MoveAllRequest Request;
typedef MoveAllResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveAll
} // namespace grasping_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::grasping_controller::MoveAll > {
  static const char* value()
  {
    return "f78f45f7e98b195bdcd2e68ec6a6f693";
  }

  static const char* value(const ::grasping_controller::MoveAll&) { return value(); }
};

template<>
struct DataType< ::grasping_controller::MoveAll > {
  static const char* value()
  {
    return "grasping_controller/MoveAll";
  }

  static const char* value(const ::grasping_controller::MoveAll&) { return value(); }
};


// service_traits::MD5Sum< ::grasping_controller::MoveAllRequest> should match 
// service_traits::MD5Sum< ::grasping_controller::MoveAll > 
template<>
struct MD5Sum< ::grasping_controller::MoveAllRequest>
{
  static const char* value()
  {
    return MD5Sum< ::grasping_controller::MoveAll >::value();
  }
  static const char* value(const ::grasping_controller::MoveAllRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::grasping_controller::MoveAllRequest> should match 
// service_traits::DataType< ::grasping_controller::MoveAll > 
template<>
struct DataType< ::grasping_controller::MoveAllRequest>
{
  static const char* value()
  {
    return DataType< ::grasping_controller::MoveAll >::value();
  }
  static const char* value(const ::grasping_controller::MoveAllRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::grasping_controller::MoveAllResponse> should match 
// service_traits::MD5Sum< ::grasping_controller::MoveAll > 
template<>
struct MD5Sum< ::grasping_controller::MoveAllResponse>
{
  static const char* value()
  {
    return MD5Sum< ::grasping_controller::MoveAll >::value();
  }
  static const char* value(const ::grasping_controller::MoveAllResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::grasping_controller::MoveAllResponse> should match 
// service_traits::DataType< ::grasping_controller::MoveAll > 
template<>
struct DataType< ::grasping_controller::MoveAllResponse>
{
  static const char* value()
  {
    return DataType< ::grasping_controller::MoveAll >::value();
  }
  static const char* value(const ::grasping_controller::MoveAllResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRASPING_CONTROLLER_MESSAGE_MOVEALL_H
