float64 x_obj
float64 y_obj
float64 z_obj
float64 xr_obj
float64 yr_obj
float64 zr_obj
float64 w_obj
float64 x_gripper
float64 y_gripper
float64 z_gripper
float64 xr_gripper
float64 yr_gripper
float64 zr_gripper
float64 w_gripper
float64 width
---
int64 error_code
