(cl:in-package grasping_controller-srv)
(cl:export '(X_OBJ-VAL
          X_OBJ
          Y_OBJ-VAL
          Y_OBJ
          Z_OBJ-VAL
          Z_OBJ
          XR_OBJ-VAL
          XR_OBJ
          YR_OBJ-VAL
          YR_OBJ
          ZR_OBJ-VAL
          ZR_OBJ
          W_OBJ-VAL
          W_OBJ
          X_GRIPPER-VAL
          X_GRIPPER
          Y_GRIPPER-VAL
          Y_GRIPPER
          Z_GRIPPER-VAL
          Z_GRIPPER
          XR_GRIPPER-VAL
          XR_GRIPPER
          YR_GRIPPER-VAL
          YR_GRIPPER
          ZR_GRIPPER-VAL
          ZR_GRIPPER
          W_GRIPPER-VAL
          W_GRIPPER
          JOINT_1-VAL
          JOINT_1
          JOINT_2-VAL
          JOINT_2
          JOINT_3-VAL
          JOINT_3
          JOINT_4-VAL
          JOINT_4
          JOINT_5-VAL
          JOINT_5
          JOINT_6-VAL
          JOINT_6
))